kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook
  namespace: jupyter
spec:
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30002
  selector:
    component: jupyter
  type: NodePort

